### ISSUE TITLE
[BUG] Plugin is not starting on Folia 1.20.6 

### ISSUE THREAD

**Issue by JavaToastDev** [Folia-Inquisitors/MoreFoWorld#9]
[20:35:22 INFO]: [MoreFoWorld] Enabling MoreFoWorld v1.7.2
[20:35:22 ERROR]: Error occurred while enabling MoreFoWorld v1.7.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/core/RegistryAccess
        at MoreFoWorld-1.7.2-all.jar/me.hsgamer.morefoworld.MoreFoWorld.enable(MoreFoWorld.java:45) ~[MoreFoWorld-1.7.2-all.jar:?]
        at MoreFoWorld-1.7.2-all.jar/me.hsgamer.morefoworld.minelib.plugin.base.BasePlugin.onEnable(BasePlugin.java:78) ~[MoreFoWorld-1.7.2-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:632) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:581) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:350) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 12 more
[20:35:22 INFO]: [MoreFoWorld] Disabling MoreFoWorld v1.7.2

**Comment by JavaToastDev** [comment]
I just saw that the last version of the plugin only supports the last version of Folia, so I downloaded the appropriate version (1.6.0) for 1.20.6 server, but this version doesn't seem to start either:

https://pastebin.com/akDCXhN0

**Comment by HSGamer** [comment]
> I just saw that the last version of the plugin only supports the last version of Folia, so I downloaded the appropriate version (1.6.0) for 1.20.6 server, but this version doesn't seem to start either:
> 
> [pastebin.com/akDCXhN0](https://pastebin.com/akDCXhN0)

Starting from 1.20.5, the Folia build steps were changed and you must use the remapped jar, not reobf jar.

**Comment by JavaToastDev** [comment]
Maybe this is a stupid question, but I haven't found any instructions on how to compile the remapped jar?
So how can I compile it?
